### ISSUE TITLE
0.7 roadmap

### ISSUE THREAD

**Issue by amirouche** [amirouche/AjguDB#5]
- [x] add `ajgudb.set` and `ajgudb.get` as a specific table in wiredtiger
- [x] add `Vertex.delete` & `Edge.delete`
- [x] add `Vertex.save` & `Edge.save`
- [x] add fuzzy search
- [ ] add timeseries over each element
- [ ] create Sphinx documentation
- [ ] make csv export compatible with `gephi`
- [ ] fix `graph-tool` and `networkx` conversion functions
- [ ] complete an conceptnet example
 - [ ] create article about conceptnet giving high level overview and statistics
 - [ ] create a summarizer (using cosimrank and lexrank?) over the bbc dataset
- [ ] make a performance review of the code

maybe:

- [ ] create a function to merge two ordered generators and move to `gremlin.vertices(label=None, **kwargs)`

**Comment by amirouche** [comment]
not relevant anymore, I will create a new roadmap later.
